made

diff --git a/backend/DockerFile b/backend/DockerFile
--- a/backend/DockerFile
+++ b/backend/DockerFile
@@ -8,6 +8,7 @@ RUN apt-get update && apt-get install -y chromium
 ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
 
 WORKDIR /usr/src/app
+RUN which chromium || echo "Chromium not found"
 
 COPY package.json ./
 RUN npm ci 
